### ISSUE TITLE
Bonders still bond withdrawals even with `dry` mode on

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#330]
In some cases, bonders will bond withdrawals even with `dry` mode enabled. As an example, search the ETH bonder log stream `63082aefe1f5fcf9f4f77b67474fcc4c7f86a567d1d3f1ff0729ab6620bb08bd` for "sent bondWithdrawal on" and "dry mode:" to see that `dry` mode is on but transactions were processed. 

The `docker.sh` file at the time was:

```
docker run \
  ...
  -v ~/.hop-node:/root \
  $docker_image \
  --config /root/config.json \
  --dry
```

**Comment by miguelmota** [comment]
The dry mode check in [`BondWithdrawalWatcher`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/BondWithdrawalWatcher.ts#L159) is the same as the other watchers (such as [`CommitTransfersWatcher`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/CommitTransfersWatcher.ts#L143), [`BondTransferRootWatcher`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/BondTransferRootWatcher.ts#L150), [`SettleBondedWithdrawalWatcher`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/SettleBondedWithdrawalWatcher.ts#L191)) and it's checked before sending the tx, so I don't think it's due to the dry mode setting. It could be related to the transfer state not properly updating

**Comment by miguelmota** [comment]
Is this still an issue? I was not able to reproduce a few weeks ago

**Comment by shanefontaine** [comment]
Yes it is. I was just able to reproduce it on the latest ETH logstream by adding `--dry` to the end of `docker.sh` and running `./docker.sh`.

**Comment by miguelmota** [comment]
@shanefontaine the dry mode state is being overridden [here](https://github.com/hop-protocol/hop/blob/1f491b0f1b0801674032c803e03fe0234db78c00/packages/hop-node/src/watchers/classes/BaseWatcher.ts#L207) which is what's causing it to keep bonding withdrawals

![DeepinScreenshot_select-area_20220125161644](https://user-images.githubusercontent.com/168240/151082230-a1831901-e0d0-41b4-ae93-7d1c310fca11.png)

![DeepinScreenshot_select-area_20220125161430](https://user-images.githubusercontent.com/168240/151081426-10632a21-53d7-4387-b92e-6f6276b4ab85.png)

I removed the stateUpdateAddress from ETH bonder (which I think is the only bonder that has it)

Two options I can think of
- Remove concept of state update address
- Don't set dry mode to false if the bonder was started with dry mode

Let me know what you think or if you have any suggestions
