### ISSUE TITLE
In-memory timestamp checks are not ideal and should be removed in order to keep watcher standardized

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#340]
Some watchers have in-memory timestamp checks. These are not ideal, as they (1) are unstandard relative to the rest of the watchers, (2) might not work as expected on bonder startup (before memory is written), and (3) are difficult to debug.

These _should be able_ to be removed, however, the updated implementation is not 100% clear to me.

Two cases where this matters:
* [`settleAttemptedAt`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/SettleBondedWithdrawalWatcher.ts#L24)
* [`commitTxSentAt`](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/watchers/CommitTransfersWatcher.ts#L27)

**Comment by miguelmota** [comment]
I think they could be moved to be a db item property to be consistent with the rest (like `bondWithdrawalAttemptedAt`) and would make debugging easier

**Comment by shanefontaine** [comment]
That might work for `commitTxSentAt` (I'm not 100% sure if there is a reason why it is not like this in the first place).

I'm not sure that works for `settleAttemptedAt`. `settleAttemptedAt` currently serves the role of `"Mark a settlement as attempted here so that multiple db reads are not attempted every poll. This comes into play when a transfer is bonded after others in the same root have been settled"`. Maybe that can be done in a more ideal way rather than an in-memory store.

I think this one requires some more thought through edge cases if/when it gets implemented.

**Comment by miguelmota** [comment]
I think the reason `commitTxSentAt` is in memory is because we don't know what the transferRootId is yet (we know what it is only after commitTransfers), so for that reason we can't update it in the db and I think we should leave it as is.

The settleAttemptedAt state has been moved to the transferRootsDb ([PR](https://github.com/hop-protocol/hop/pull/386)). I think it was in memory because in the past we were indexing by transferRootHash and not by transferRootId and the db getters weren't as efficient.

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/386
