### ISSUE TITLE
TransferRoot DB items are indexed by `committedAt` timestamp but it might not always be the case that `committedAt` exists in order to index the entry

### ISSUE THREAD

**Issue by shanefontaine** [hop-protocol/hop#341]
_This issue was inspired by [this discussion](https://github.com/hop-protocol/hop/pull/318#discussion_r769187693)._

We currently index transfer roots [by their `committedAt` timestamp](https://github.com/hop-protocol/hop/blob/f10a3234399581b021239e4fbfb39c135f8bc50e/packages/hop-node/src/db/TransferRootsDb.ts#L297) and act on these DB entries accordingly. This works most of the time. However, there are edge cases where a malicious bonder will bond an invalid `transferRoot` that was never committed. In this case, there will be no `committedAt` timestamp to index the DB entry by.

I believe the implications of a change like this would be large, so it is worth a discussion and general consensus prior to implementation.

**Comment by miguelmota** [comment]
@shanefontaine  Since we store the `bondedAt` timestamp in db, we can add another sub db to index by the bonded timestamp. In `getChallengeableTransferRoots` we can then retrieve a list of transferRootIds by querying this sub (`subDbBondedAt`) to get the transfer root db items. It's a pretty simple addition but let me know what you think

**Comment by miguelmota** [comment]
Closed by https://github.com/hop-protocol/hop/pull/366
