### ISSUE TITLE
`yarn` or `npm`?

### ISSUE THREAD

**Issue by zhyd1997** [hop-protocol/hop#447]
the `engine` is `yarn` but we 're using `npm`?

https://github.com/hop-protocol/hop/blob/23e814391125405ac60a477fee2f82d9c950ef44/package.json#L4-L7

**Comment by miguelmota** [comment]
I think we want to keep npm as the package installer for all the packages for simplicity. I believe only the frontend package uses yarn because removing the yarn lock file breaks some things at the moment. The yarn engine here must have been an artifact from copy/pasting the package.json from another package

**Comment by zhyd1997** [comment]
> I think we want to keep npm as the package installer for all the packages for simplicity. I believe only the frontend package uses yarn because removing the yarn lock file breaks some things at the moment. The yarn engine here must have been an artifact from copy/pasting the package.json from another package

agree.

**Comment by zhyd1997** [comment]
If there's a plan to use `pnpm`, this should be not an issue anymore.
